### ISSUE TITLE
The script failing to generate new resolve.conf

### ISSUE THREAD

**Issue by stephencheng** [aw1cks/openconnect#3]
@aw1cks Could you help me understand a littlbe bit of the following code:

```
  RESOLV_CONFIG=$(grep -v '^nameserver' /etc/resolv.conf | grep -v search)
  ORIGINAL_SEARCH_DOMAINS=$(grep '^search' /etc/resolv.conf)
  NEW_SEARCH_DOMAINS="${ORIGINAL_SEARCH_DOMAINS} ${SEARCH_DOMAINS}"
  NEW_NAMESERVER_CONF='nameserver 127.0.0.1'
  sudo cp /etc/resolv.conf /etc/resolv.conf.orig
  printf "%s\n%s\n%s\n" "${RESOLV_CONFIG}" "${NEW_SEARCH_DOMAINS}" "${NEW_NAMESERVER_CONF}" | sudo tee /etc/resolv.conf > /dev/null 2>&1
```

Basically this is what I have in resolve.conf
```

  #
  # macOS Notice
  #
  # This file is not consulted for DNS hostname resolution, address
  # resolution, or the DNS query routing mechanism used by most
  # processes on this system.
  #
  # To view the DNS configuration used by this system, use:
  #   scutil --dns
  #
  # SEE ALSO
  #   dns-sd(1), scutil(8)
  #
  # This file is automatically generated.
  #
  nameserver 208.67.222.222
  nameserver 8.8.8.8

```

What I found is that this step is failing `ORIGINAL_SEARCH_DOMAINS=$(grep '^search' /etc/resolv.conf)` due to found nothing there, then it will not produce new resolve.conf

I would like to understand what kind of forward the new resolve.conf will look like. Provided with my above resolve.conf,what should be the new resolve.conf

Thanks

Btw, this is a awesome work!!!

**Comment by aw1cks** [comment]
Hi @stephencheng .

That is specifically designed to work for Linux - as per that comment in your resolv.conf, it looks like the process would be different on MacOS. I don't actually have a Mac so it's not something I would easily be able to test.

Effectively though, on Linux, all that's happening, is that any existing search domains are grabbed from the original file, appended to our list of search domains, then the original file is copied to another file to keep its contents, and we create our own `resolv.conf` to point to `127.0.0.1`, with any new search domains as well as the existing stuff.

So in your example it would look like this:
```
search <search domains passed as variable to container>
nameserver 127.0.0.1
```
Although this may not be particularly helpful on MacOS given the comment in that file.

But yes, I think it may need some extra error handling, to handle the case where NO search domains are present, like in your case.

**Comment by aw1cks** [comment]
Closing in favour of https://github.com/aw1cks/openconnect/issues/5
