### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by bmitchinson** [aw1cks/openconnect#5]
Hey there, thanks for your work on this.

I'm like 90% of the way there to getting this working on mac, would love some advice and then maybe I could update the docs.

Inside the docker container, I successfully connect to the VPN. I'm also able to `nslookup` and `wget` a webpage that's accessible only on the vpn as a result.

```
# bash from within the container

/vpn # wget --no-check-certificate READACTED_URL
Connecting to READACTED_URL (READACTED_IP)
saving to 'index.html'
index.html           100% |**********************************************************************************************|  3381  0:00:00 ETA
'index.html' saved

/vpn # nslookup READACTED_URL
Server:         167.240.253.3
Address:        167.240.253.3:53

Non-authoritative answer:
*** Can't find READACTED_URL: No answer

Non-authoritative answer:
Name:   READACTED_URL
Address: READACTED_IP
```

I can't get my mac to benefit from the container. 

I'd expect an nslookup that specifies to use the container as a dns registry to yield the same results as inside the container, but it times out.

```
# from mac
❯ docker ps
CONTAINER ID   IMAGE                COMMAND                CREATED          STATUS                    PORTS                  NAMES
81031ba77b7c   aw1cks/openconnect   "/vpn/entrypoint.sh"   13 minutes ago   Up 13 minutes (healthy)   127.0.0.1:53->53/udp   vpn

❯ nslookup REDACTED URL 127.0.0.1
;; connection timed out; no servers could be reached
```

Any ideas on how to get nslookup from outside the container working? 

If you run nslookup from outside the container on linux, specifying 127.0.0.1 as the dns address, does that work?

Thanks for taking time to look at my question 👍

**Comment by bmitchinson** [comment]
Moments after posting this, I realized I was missing a DNS name from the SEARCH_DOMAINS, and so dnsmasq was rejecting my nslookup, that fixed it! Once I get the system preferences working to reflect 127.0.0.1 I'll follow up here

**Comment by bmitchinson** [comment]
With the docker container running, using the run script to execute `ip route add` (with `https://github.com/brona/iproute2mac` as a mac stand in), I get the following route entries:

```
# outside of the container, on host mac machine

❯ sudo ip route
Password:
default via 192.168.0.1 dev en0
{REDACTED_IP}/32 via 172.17.0.2 dev en0
127.0.0.0/8 via 127.0.0.1 dev lo0
127.0.0.1/32 via 127.0.0.1 dev lo0
```

This seems to be the proper setup to route traffic to the IP address of the container, right?

DNS seems to be working great, because on mac I can resolve the dscacheutil request, which is like `nslookup`, but ensured to use mac network settings by default, like browsers would.

```
# outside of the container, on host mac machine

❯ dscacheutil -q host -a name REDACTED_URL
name: REDACTED_URL
ip_address: REDACTED_IP
```

**Comment by bmitchinson** [comment]
Additional confirmation that route tables appear to be setup fine, despite the container not relaying the traffic properly:

```
❯ sudo route get REDACTED_IP
   route to: REDACTED_IP
destination: REDACTED_IP
    gateway: 172.17.0.2
  interface: en0
      flags: <UP,GATEWAY,HOST,DONE,STATIC>
 recvpipe  sendpipe  ssthresh  rtt,msec    rttvar  hopcount      mtu     expire
       0         0         0         0         0         0      1500         0
```

**Comment by bmitchinson** [comment]
Ping reflecting success resolving DNS IP, but unable to reach destination URL

``` bash
# from outside the container, running on mac host:

❯ ping REDACTED_URL
PING REDACTED_URL (REDACTED_IP): 56 data bytes
ping: sendto: Network is unreachable
Request timeout for icmp_seq 0
ping: sendto: Network is unreachable
Request timeout for icmp_seq 1
ping: sendto: Network is unreachable
Request timeout for icmp_seq 2
...
5 packets transmitted, 0 packets received, 100.0% packet loss

❯ ping mitchinson.dev
PING mitchinson.dev (172.67.174.85): 56 data bytes
64 bytes from 172.67.174.85: icmp_seq=0 ttl=51 time=31.503 ms
64 bytes from 172.67.174.85: icmp_seq=1 ttl=51 time=129.721 ms
64 bytes from 172.67.174.85: icmp_seq=2 ttl=51 time=93.158 ms
^C
--- mitchinson.dev ping statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 31.503/72.844/129.721/40.749 ms
```

**Comment by aw1cks** [comment]
Hey, thanks for reaching out

I can't easily test at the moment on Mac, so would need some help on your side to get this working 100%. Definitely happy to take any pull requests!

I'm not 100% with how the networking is set up with Docker on Mac. Maybe try seeing if you can ping the IP of the container first? If that succeeds, try using wireshark/tcpdump while trying to reach your redacted IP - you should be able to use wireshark from the Mac to see what's going on with your outbound traffic towards that redacted IP. Then try tcpdump inside the container to see if the traffic is reaching the container and what's going on there. the redacted IP definitely can be pinged from inside the container?

Good luck

**Comment by bmitchinson** [comment]
Hm didn't get an email with your response, sorry about that.

I ended up combining some of the logic here with this https://github.com/jlesage/docker-firefox

I just do all my work from inside of the container and on a browser running off the container, instead of relaying the connection to my host mac with dsnmasq in the container.

Dsnmasq would be the preferred route, but I doubt I'll have time to get back to picking this up.

Thanks for your response though, your documentation of openconnect was instrumental in solving my problem.
